language: node_js
cache: npm
node_js:
  - '14'

services:
  - docker

sudo: false

branches:
  only:
    - master

install:
  - npm install

script:
  - docker-compose run build_wasm
  - docker-compose run build_web

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  on:
    branch: gh-pages

